# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'STANTAO' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for STANTAO

    pod 'Masonry'
    
    pod 'SDWebImage'
    
    pod 'MBProgressHUD'
    
    pod 'AFNetworking'
    
    pod 'MJExtension'

    pod 'ReactiveCocoa', '~> 2.5'

#    pod  'SwipeBack'
    
#    pod 'FXBlurView'

    pod 'XMLDictionary'
    
    pod 'SWTableViewCell'
  target 'STANTAOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'STANTAOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
